
[Supplementary materials]


*   https://people.duke.edu/~ccc14/sta-663-2020/
*   https://github.com/cliburn/sta-663-2020 ​
*   https://sta663-sp22.github.io/
*   https://github.com/jakevdp/PythonDataScienceHandbook/tree/master/notebooks ​
*   https://github.com/jonkrohn/ML-foundations/tree/master/notebooks
*   https://github.com/ageron/handson-ml3
*   https://github.com/joelgrus/data-science-from-scratch/tree/master/scratch


In [ ]:
!wget 'https://drive.google.com/uc?export=download&id=1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb' -O data.csv

--2022-11-16 01:38:17--  https://drive.google.com/uc?export=download&id=1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb
Resolving drive.google.com (drive.google.com)... 74.125.134.102, 74.125.134.101, 74.125.134.138, ...
Connecting to drive.google.com (drive.google.com)|74.125.134.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0g-a8-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/3k1p24ld3q8u2pp8jkmhjfj0nevh47t2/1668562650000/17823811839281681652/*/1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb?e=download&uuid=26fbab30-188b-49e2-bcde-3ebe1b9a4550 [following]
--2022-11-16 01:38:18--  https://doc-0g-a8-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/3k1p24ld3q8u2pp8jkmhjfj0nevh47t2/1668562650000/17823811839281681652/*/1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb?e=download&uuid=26fbab30-188b-49e2-bcde-3ebe1b9a4550
Resolving doc-0g-a8-docs.googleusercontent.com (doc-0g-a8-docs.googleusercontent.com)... 172.217.204.132, 2607

In [ ]:
%cd /content/drive/MyDrive/DataScience_111

/content/drive/MyDrive/DataScience_111


***************   2022 /09 /28    **********************

In [ ]:
print("Hello, world")

Hello, world


In [ ]:
!pwd
!ls

/content
drive  sample_data


In [ ]:
%cd '/content/drive/MyDrive/DataScience_111'

/content/drive/MyDrive/DataScience_111


In [ ]:
!git clone https://github.com/leriomaggio/python-in-a-notebook

fatal: destination path 'python-in-a-notebook' already exists and is not an empty directory.


In [ ]:
!git clone https://github.com/Pierian-Data/Complete-Python-3-Bootcamp

Cloning into 'Complete-Python-3-Bootcamp'...
remote: Enumerating objects: 780, done.
remote: Total 780 (delta 0), reused 0 (delta 0), pack-reused 780
Receiving objects: 100% (780/780), 36.25 MiB | 12.93 MiB/s, done.
Resolving deltas: 100% (325/325), done.
Checking out files: 100% (393/393), done.


In [ ]:
message = "Hello world"
name = "HWCHIU"
print(message + "," + name + ". Do you enjoy python?" )

Hello world,HWCHIU. Do you enjoy python?


In [ ]:
first_name = 'eric'

print(first_name)
print(first_name.title())
print(first_name.upper())
print(first_name.upper() + '\n'*10 + first_name.upper())

eric
Eric
ERIC
eric









eric


***************   2022 /10 /05    **********************

In [ ]:
message = "Hello world"
name = input("Hello, what is your name?  ") 
print(message + "," + name + ". Do you enjoy python?" )

Hello, what is your name?  HwCHIU
Hello world,HwCHIU. Do you enjoy python?


In [ ]:
message = "Hello"
height = input("Hello, how tall are you in cm?  ") 
print(message + "," + name + ". Your height is " + height + " feet.")

Hello, how tall are you in cm?  180
Hello,HwCHIU. Your height is 180 feet.


In [ ]:
message = "Hello"
height = input("Hello, how tall are you in cm?  ") 
height_ft = print(float(int(height)/30))
print(message + "," + name + ". Your height is " + str(int(height)/30) + " feet.")

Hello, how tall are you in cm?  180
6.0
Hello,HwCHIU. Your height is 6.0 feet.


In [ ]:
print(101*4)
print("101"*4)

404
101101101101


Rotate (1,2) by 90 degree.

In [ ]:
Z = complex(1,2)
print(Z*complex(0,1))

(-2+1j)


In [ ]:
print((-2+1j)*1j)

(-1-2j)


In [ ]:
int(float(181/30)*100)/100

6.03

In [ ]:
import math,cmath
math.sin(3)
#math.exp(complex(1,2))
#math.exp(Z)
print(cmath.exp(Z))
2**Z

(-1.1312043837568135+2.4717266720048188j)


(0.36691394948660344+1.9660554808224875j)

In [ ]:
s1 = "Python is so awesome." 
print(s1.title())
print(s1.lower())
print(s1.lower().title()[:6:][1::2])
print(s1.lower().title()[:6:][::-1].upper())
print(s1)



Python Is So Awesome.
python is so awesome.
yhn
NOHTYP
Python is so awesome.


In [ ]:
#print(s1.index("so"))
print(s1[10])
print(s1.find("So"))
print(s1.find("so"))
print(s1.replace("so", "SO"))

s
-1
10
Python is SO aweSOme.


In [ ]:
type(s1.split(" "))
list_s1 = s1.split(" ")[::-1]
#print(s1.split(" ")[::-1].reverse())   ## wrong code
#print(list_s1.reverse())     ## reverse method change the object in place and return None
print(list_s1)
"-".join(list_s1)


['awesome.', 'so', 'is', 'Python']


'awesome.-so-is-Python'

Homework 2022/10/05
1. Generate any random alphabet.
2. Generate any upper and lower alphabet.

2022/10/12 String and LIST


> List indexing without index numbers



In [ ]:
str_total = str()
str_total = ""
for x in list_s1:
  #str_total = str_total + x
  str_total += x + " "

print(str_total)
#  print(x + "\n")
#  print(x,end=' ')


awesome. so is Python 


> List indexing specifies index numbers in for loop

In [ ]:
str_total = ""
for i in range(3,-1,-1):
 str_total += list_s1[i] + " "
print(str_total)

Python is so awesome. 


Direct indexing using bracket []

In [ ]:
list_s1[::-1]

['Python', 'is', 'so', 'awesome.']

Condion expression

In [ ]:
a = True
b = 0

if a:
    print("a is true! ")
if not b:
    print("b is false! ")
if a and b:
    print("a and b are true! ")
if a or b:
    print("a or b is true! ")

if a:
  print("a is true! ")
if a & b:
  print("a and b are true! ")
if a | b:
  print("a or b is true!")

a is true! 
b is false! 
a or b is true! 
a is true! 
a or b is true!


In [ ]:
print(not(b))
print(a and b)
#print(and(a,b))

True
0


2022/10/19 Condition

In [ ]:
print(len("hello"))
print(list(range(1,5,1)))

len("hello") > 4

if len("hello") > 4:
  print("True")

len("hello") > 4 
len("world") > 4 

print(len("hello") > 4 and len("world") > 4 )

print(4 & False)

print(len("hello") > 4 & len("world") > 4 )
print((len("hello") > 4) & (len("world") > 4 ))

#print((len("hello") eq 4) & (len("world") > 4 ))

5
[1, 2, 3, 4]
True
True
0
False
True


Conditon expression excution

In [ ]:
degree =input("What is your degree : ")

if degree[0].lower() == "p" :
  print("You're qulified!")



What is your degree : ppte
You're qulified!


In [ ]:
lang =input("What is your skillful programming language : ")
lang_score_dict = {"R":3.3,"Python":2.8, "Java":2.1}
score_lang = lang_score_dict[lang.capitalize()]
score_lang*2

What is your skillful programming language : python


5.6

In [ ]:
year  = 10
1 +  ( year > 5 ) * ( year - 5 ) * 2/5   

3.0

In [ ]:
for num in range(10,20):
    if num%2 == 0:
        continue
    for i in range(3,num):
        if num%i == 0: 
            break
    else: 
        print(str(num) + 'is a prime number')

11is a prime number
13is a prime number
17is a prime number
19is a prime number


In [ ]:
for i in range(1,10):
  print(i)
print("Ending")

In [ ]:
for m in range(1,100,2):
  print(m*2)

In [ ]:
import math
x = [(m > 5)* m for m in range(1,100,2)]
x

2022/10/26 Lecture 5

In [ ]:
[z**2 for z in range(10) if z>4]

[25, 36, 49, 64, 81]

Note that the function output is to return or to write back.

In [ ]:
x = [5, 3, 8, 6]
y = [12, 13]
print(x + y)

print(x.extend(y))
print("Extend output : " + str(x))
x = [5, 3, 8, 6]
y = [12, 13]
print(x.append(y))
print("Append output : " + str(x))
print(x[4][1])
x = [5, 3, 8, 6]

print("Pop output1 : " + str(x.pop()))
print("Pop output2 : " + str(x))
x.reverse()
print("Reverse output2 : " + str(x))

[5, 3, 8, 6, 12, 13]
None
Extend output : [5, 3, 8, 6, 12, 13]
None
Append output : [5, 3, 8, 6, [12, 13]]
13
Pop output1 : 6
Pop output2 : [5, 3, 8]
Reverse output2 : [8, 3, 5]


In [ ]:
#x_list.index(33.9)
x_list.count("beef")
x_list.count("Beef")
("Beef" in x_list )*10

0

In [ ]:
sum_ = 0
for x in range(1,11,1):
  sum_ += x
print(sum_)

55


In [ ]:
#del sum
sum(range(1,11,1))

55

In [ ]:
x_number  = 25.3
x_string = "port"
x_list = ["pork", 25.3, "beef", 33.8, 'chicken', 22.7]
x_dict = {'pork':25.3, 'beef':33.8, 'chicken':22.7}

In [ ]:
print(list(enumerate(x_list)))
for index, item in enumerate(x_list):
	print(index, item)

[(0, 'pork'), (1, 25.3), (2, 'beef'), (3, 33.8), (4, 'chicken'), (5, 22.7)]
0 pork
1 25.3
2 beef
3 33.8
4 chicken
5 22.7


Convert a list to a dict

In [ ]:
#print(dict(x_list))
print(dict(enumerate(x_list)))

{0: 'pork', 1: 25.3, 2: 'beef', 3: 33.8, 4: 'chicken', 5: 22.7}


In [ ]:
#y_dict = dict(enumerate(x_list))
#y_dict[2:4]

In [ ]:
x_list = ["pork", 25.3, "beef", 33.8, 'chicken', 22.7]
x_list_dict = dict(zip(x_list[0::2],x_list[1::2]))
#x_list_dict.has_key("pork")
"pork" in x_list_dict
25.3 in x_list_dict
print(list(x_list_dict.keys()))
print(list(x_list_dict.values()))
25.3 in x_list_dict.values()

y_list = list(x_list_dict.items())
print(y_list[0])

['pork', 'beef', 'chicken']
[25.3, 33.8, 22.7]
('pork', 25.3)


In [ ]:
x_dict = {'pork':25.3, 'beef':33.8, 'chicken':22.7}
data_sort = sorted(x_dict.items(),key=lambda d:d[1],reverse = True)
print(data_sort)
x_dict = {'pork':25.3, 'beef':33.8, 'chicken':22.7}
data_sort = sorted(x_dict.items(),key=lambda d:d[0])
print(data_sort)

[('beef', 33.8), ('pork', 25.3), ('chicken', 22.7)]
[('beef', 33.8), ('chicken', 22.7), ('pork', 25.3)]


In [ ]:
x ={'446' :25.3, '123':33.8,'678':22.7}
data_sort=sorted(x.items(),key=lambda d:int(d[0]),reverse = True)
print(data_sort)


[('678', 22.7), ('446', 25.3), ('123', 33.8)]


In [ ]:
x = lambda a : a + 10
print(x(5))
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))
x = lambda a : a + 10
#print(x([5, 6, 2]))

def square(x) :      
    return x ** 2

print(list(map(square, [1,2,3,4,5])))

print(list(map(lambda x: x*10, [1,2,3,4,5])))

15
13
[1, 4, 9, 16, 25]
[10, 20, 30, 40, 50]


IMPORT JSON

In [ ]:
# import urllib library
from urllib.request import urlopen
from pprint import pprint
# import json
import json
# store the URL in url as 
# parameter for urlopen
#url = "https://api.github.com"
url = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=tse_2330.tw&json=1&delay=0"
  
# store the response of URL
response = urlopen(url)
  
# storing the JSON response 
# from url in data
#data_json = response.read()
#print(data_json['msgArray'][0])

data_json = json.loads(response.read())
#pprint(data_json['msgArray'][0])
pprint(data_json['msgArray'][0]['f'])

'911_238_270_268_880_'


Variious datatype comupation

In [ ]:
sum(range(1,100000001))

5000000050000000

In [ ]:
np.linspace(1,1000000000,1000000000).sum()

5.000000005e+17

In [ ]:
np.array(range(1,100000001)).sum()

5000000050000000

In [ ]:
import pandas as pd
sum(pd.array(range(1,101)))

5050

In [ ]:
import torch
torch.linspace(1,1000000000,1000000000).sum()

tensor(5.0000e+17)

In [ ]:
import tensorflow as tf
#tf.linspace(1,1000000,1000000)

IMPORT CSV

In [ ]:
%cd  '/content/drive/MyDrive/Courses/Linux_111'
!pwd

/content/drive/MyDrive/Courses/Linux_111
/content/drive/MyDrive/Courses/Linux_111


In [ ]:
!wget 'https://drive.google.com/uc?export=download&id=1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb' -O data.csv

--2022-11-16 00:49:02--  https://drive.google.com/uc?export=download&id=1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb
Resolving drive.google.com (drive.google.com)... 173.194.214.101, 173.194.214.138, 173.194.214.100, ...
Connecting to drive.google.com (drive.google.com)|173.194.214.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0g-a8-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/2hn4625pcssjiqpqps489v074qbh6fro/1668559725000/17823811839281681652/*/1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb?e=download&uuid=90443c26-d410-4d41-bd84-5a00f9477964 [following]
--2022-11-16 00:49:03--  https://doc-0g-a8-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/2hn4625pcssjiqpqps489v074qbh6fro/1668559725000/17823811839281681652/*/1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb?e=download&uuid=90443c26-d410-4d41-bd84-5a00f9477964
Resolving doc-0g-a8-docs.googleusercontent.com (doc-0g-a8-docs.googleusercontent.com)... 173.194.218.132, 

In [ ]:
#!cat data.csv
!head -n 10 data.csv | tail -n 1 

9,Julie Chen,100,92,94,92,91,100,97,99


In [ ]:
import csv
# 開啟 CSV 檔案
from pprint import pprint
with open('data.csv', newline='') as csvfile:
  # 讀取 CSV 檔案內容
  rows = csv.reader(csvfile)

  scores_list = list(rows)
  pprint(scores_list, compact =True)
  pprint(scores_list[9][2:])
  pprint(sum(map(lambda x: float(x),scores_list[9][2:10])))


[['\ufeffID', 'Full Name', 'Chinese', 'English', 'Math',
  'Physical and chemical', 'Geophaphy', 'History', 'Physics', 'Civics', 'Bonus',
  'Final1', 'Final2'],
 ['1', 'Nicola Chu', '77', '89', '89', '95', '100', '100', '97.5', '90', '?',
  '91.525', '91.075'],
 ['2', 'Karen Wu', '75', '98', '94', '87.5', '90', '97.5', '100', '96', '?',
  '91.075', '90.8'],
 ['3', 'Fiona Wu', '74', '90', '73', '85', '97.5', '95', '92.5', '92', '?',
  '86.2875', '85.725'],
 ['4', 'Susan Lu', '40', '23', '42', '40', '32.5', '40.5', '55', '26', '?',
  '41.075', '38.7375'],
 ['5', 'Claire Lin', '55', '29', '69', '62.5', '75', '66.5', '92.5', '86', '?',
  '64.6', '65.275'],
 ['6', 'Sharon Chiu', '74', '81', '80', '82.5', '90', '93', '95', '98', '?',
  '84.6875', '84.075'],
 ['7', 'Angela Chen', '69', '87', '70', '67.5', '85', '95', '90', '84', '?',
  '80.5875', '80.925'],
 ['8', 'Gillian Lin', '54', '66', '35', '65', '80', '98', '92.5', '92', '?',
  '70.625', '70.7625'],
 ['9', 'Julie Chen', '88', '87', '10

How to withdraw column data  

In [ ]:
import numpy as np
trans_np = np.genfromtxt("data.csv", delimiter=',')

sum(trans_np[9][2:])
trans_np[9][2:].sum()
pprint(f"Wrong  : {trans_np[9:][2]}", width = 200, compact=True)
print("Wrong  : " + str(trans_np[9:][2]))
print(f"Correct : {trans_np[9:,2]}")
print(f"Correct : {trans_np[9:,2]}")

print(trans_np.shape)
print(trans_np.ndim)
print(trans_np.size)
print(len(trans_np))

print(f"List 2, 5 8 \n scores : {trans_np[[2,5,8],2:]}")



'Wrong  : [11.       nan 19.    40.     6.    35.    37.5   38.5   60.    24.\n    nan 36.475 34.475]'
Wrong  : [11.       nan 19.    40.     6.    35.    37.5   38.5   60.    24.
    nan 36.475 34.475]
Correct : [88. 54. 19. 51. 68. 60. 45. 68. 32. 57. 80. 68. 69. 57. 39. 49. 59. 64.
 46.]
Correct : [88. 54. 19. 51. 68. 60. 45. 68. 32. 57. 80. 68. 69. 57. 39. 49. 59. 64.
 46.]
(28, 13)
2
364
28
List 2, 5 8 
 scores : [[ 75.      98.      94.      87.5     90.      97.5    100.      96.
       nan  91.075   90.8   ]
 [ 55.      29.      69.      62.5     75.      66.5     92.5     86.
       nan  64.6     65.275 ]
 [ 54.      66.      35.      65.      80.      98.      92.5     92.
       nan  70.625   70.7625]]


In [ ]:
scores_np = trans_np[1:,2:10]
total = np.array([scores_np[i].sum() for i in range(0,len(trans_np)-1)])
len(total)
print(total)
max_id = np.where(total == total.max())[0][0]
print(scores_list[max_id+1][1])
total[max_id]

[737.5 738.  699.  299.  535.5 693.5 647.5 582.5 767.5 644.  260.  499.
 694.  568.  610.5 721.  568.  624.  713.5 663.  565.  559.  506.  549.5
 643.5 666.5 619. ]
Julie Chen


767.5

In [ ]:
Random bool pattern

In [ ]:
import numpy as np
#import random as random
np.random.randint(2,size=8)

array([0, 1, 1, 1, 0, 1, 0, 1])

In [ ]:
scores_np[1,np.random.randint(2,size=9)]

array([75.,  2.,  2., 75., 75., 75., 75., 75., 75.])

In [ ]:
np_test = np.array(np.random.randint(2,size=8),dtype=bool)
np_test 

array([ True, False,  True, False,  True, False, False,  True])

In [ ]:
scores_np

array([[  1. ,  77. ,  89. ,  89. ,  95. , 100. , 100. ,  97.5,  90. ],
       [  2. ,  75. ,  98. ,  94. ,  87.5,  90. ,  97.5, 100. ,  96. ],
       [  3. ,  74. ,  90. ,  73. ,  85. ,  97.5,  95. ,  92.5,  92. ],
       [  4. ,  40. ,  23. ,  42. ,  40. ,  32.5,  40.5,  55. ,  26. ],
       [  5. ,  55. ,  29. ,  69. ,  62.5,  75. ,  66.5,  92.5,  86. ],
       [  6. ,  74. ,  81. ,  80. ,  82.5,  90. ,  93. ,  95. ,  98. ],
       [  7. ,  69. ,  87. ,  70. ,  67.5,  85. ,  95. ,  90. ,  84. ],
       [  8. ,  54. ,  66. ,  35. ,  65. ,  80. ,  98. ,  92.5,  92. ],
       [  9. ,  88. ,  87. , 100. ,  97.5,  95. , 100. , 100. , 100. ],
       [ 10. ,  54. ,  79. ,  75. ,  75. ,  92. ,  88. ,  95. ,  86. ],
       [ 11. ,  19. ,  40. ,   6. ,  35. ,  37.5,  38.5,  60. ,  24. ],
       [ 12. ,  51. ,  45. ,  71. ,  70. ,  67.5,  57.5,  65. ,  72. ],
       [ 13. ,  68. ,  76. ,  82. ,  75. ,  95. , 100. , 100. ,  98. ],
       [ 26. ,  60. ,  73. ,  61. ,  60. ,  75. ,  76.5,  92.5, 

Select data using boolean logic filter

In [ ]:
import numpy as np
trans_np = np.genfromtxt("data.csv", delimiter=',')
scores_np = trans_np[1:,[0]+list(range(2,10))]
random_select = np.array(np.random.randint(2,size=9),dtype=bool)
scores_np[1,random_select]
#scores_np[1,[np.random.randint(2,size=8)]]
 

array([  2.,  98.,  94., 100.,  96.])

In [ ]:
scores_np[:,3]

array([ 89.,  94.,  73.,  42.,  69.,  80.,  70.,  35., 100.,  75.,   6.,
        71.,  82.,  61.,  67.,  87.,  69.,  66.,  83.,  75.,  54.,  67.,
        26.,  56.,  84.,  74.,  67.])

Boolean list of the students  failed in Math.

In [ ]:
scores_np[:,3] < 60

array([False, False, False,  True, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False,  True,  True, False, False, False])

In [ ]:
scores_np[scores_np[:,3] < 60 ,3]

array([42., 35.,  6., 54., 26., 56.])

In [ ]:
scores_np[scores_np[:,3] < 60 ,0]

array([ 4.,  8., 11., 33., 35., 36.])

The History scores of the students failed in Math.

In [ ]:
scores_np[ scores_np[:,3] < 60  ,7]

array([55. , 92.5, 60. , 82.5, 90. , 85. ])